/** utils.test
 * project: react-mis-configurator-component
 * author: Chris Sprance - csprance
 * description:
 */
import * as utils from './utils';
import { factionGameRulesLawmenOutlawFactionTemplate } from './constants';

const mockGameRules = {
	g_gameRules_faction0: '1',
	g_gameRules_faction0_name: 'survivors',
	g_gameRules_faction0_steamids: '',
	g_gameRules_faction0_dmg_f0: '1',
	g_gameRules_faction0_dmg_f1: '1',
	g_gameRules_faction0_dmg_f2: '1',
	g_gameRules_faction0_dmg_f3: '1',
	g_gameRules_faction0_dmg_f4: '1',
	g_gameRules_faction0_dmg_f5: '1',
	g_gameRules_faction0_dmg_f6: '1',
	g_gameRules_faction1: '1',
	g_gameRules_faction1_name: 'environment',
	g_gameRules_faction1_steamids: '',
	g_gameRules_faction1_dmg_f0: '1',
	g_gameRules_faction1_dmg_f1: '1',
	g_gameRules_faction1_dmg_f2: '1',
	g_gameRules_faction1_dmg_f3: '1',
	g_gameRules_faction1_dmg_f4: '1',
	g_gameRules_faction1_dmg_f5: '1',
	g_gameRules_faction1_dmg_f6: '1',
	g_gameRules_faction2: '1',
	g_gameRules_faction2_name: 'bases',
	g_gameRules_faction2_steamids: '',
	g_gameRules_faction2_dmg_f0: '1',
	g_gameRules_faction2_dmg_f1: '1',
	g_gameRules_faction2_dmg_f2: '1',
	g_gameRules_faction2_dmg_f3: '1',
	g_gameRules_faction2_dmg_f4: '1',
	g_gameRules_faction2_dmg_f5: '1',
	g_gameRules_faction2_dmg_f6: '1',
	g_gameRules_faction3: '0',
	g_gameRules_faction3_name: 'lawmen',
	g_gameRules_faction3_steamids: '',
	g_gameRules_faction3_dmg_f0: '1',
	g_gameRules_faction3_dmg_f1: '1',
	g_gameRules_faction3_dmg_f2: '1',
	g_gameRules_faction3_dmg_f3: '1',
	g_gameRules_faction3_dmg_f4: '1',
	g_gameRules_faction3_dmg_f5: '1',
	g_gameRules_faction3_dmg_f6: '1',
	g_gameRules_faction4: '0',
	g_gameRules_faction4_name: 'outlaws',
	g_gameRules_faction4_steamids: '',
	g_gameRules_faction4_dmg_f0: '1',
	g_gameRules_faction4_dmg_f1: '1',
	g_gameRules_faction4_dmg_f2: '1',
	g_gameRules_faction4_dmg_f3: '1',
	g_gameRules_faction4_dmg_f4: '1',
	g_gameRules_faction4_dmg_f5: '1',
	g_gameRules_faction4_dmg_f6: '1',
	g_gameRules_faction5: '0',
	g_gameRules_faction5_name: 'military',
	g_gameRules_faction5_steamids: '',
	g_gameRules_faction5_dmg_f0: '1',
	g_gameRules_faction5_dmg_f1: '1',
	g_gameRules_faction5_dmg_f2: '1',
	g_gameRules_faction5_dmg_f3: '1',
	g_gameRules_faction5_dmg_f4: '1',
	g_gameRules_faction5_dmg_f5: '1',
	g_gameRules_faction5_dmg_f6: '1',
	g_gameRules_faction6: '0',
	g_gameRules_faction6_name: 'corporate',
	g_gameRules_faction6_steamids: '',
	g_gameRules_faction6_dmg_f0: '1',
	g_gameRules_faction6_dmg_f1: '1',
	g_gameRules_faction6_dmg_f2: '1',
	g_gameRules_faction6_dmg_f3: '1',
	g_gameRules_faction6_dmg_f4: '1',
	g_gameRules_faction6_dmg_f5: '1',
	g_gameRules_faction6_dmg_f6: '1',
};

export const mockGameRulesLawmenOutlawFactionTemplate = {
	g_gameRules_faction0: '0',
	g_gameRules_faction0_name: 'survivors',
	g_gameRules_faction0_steamids: '',
	g_gameRules_faction0_dmg_f0: '1',
	g_gameRules_faction0_dmg_f1: '1',
	g_gameRules_faction0_dmg_f2: '0',
	g_gameRules_faction0_dmg_f3: '0',
	g_gameRules_faction0_dmg_f4: '1',
	g_gameRules_faction0_dmg_f5: '1',
	g_gameRules_faction0_dmg_f6: '1',
	g_gameRules_faction1: '1',
	g_gameRules_faction1_name: 'environment',
	g_gameRules_faction1_steamids: '',
	g_gameRules_faction1_dmg_f0: '1',
	g_gameRules_faction1_dmg_f1: '1',
	g_gameRules_faction1_dmg_f2: '1',
	g_gameRules_faction1_dmg_f3: '1',
	g_gameRules_faction1_dmg_f4: '1',
	g_gameRules_faction1_dmg_f5: '1',
	g_gameRules_faction1_dmg_f6: '1',
	g_gameRules_faction2: '1',
	g_gameRules_faction2_name: 'bases',
	g_gameRules_faction2_steamids: '',
	g_gameRules_faction2_dmg_f0: '1',
	g_gameRules_faction2_dmg_f1: '1',
	g_gameRules_faction2_dmg_f2: '1',
	g_gameRules_faction2_dmg_f3: '1',
	g_gameRules_faction2_dmg_f4: '1',
	g_gameRules_faction2_dmg_f5: '1',
	g_gameRules_faction2_dmg_f6: '1',
	g_gameRules_faction3: '1',
	g_gameRules_faction3_name: 'lawmen',
	g_gameRules_faction3_steamids: '',
	g_gameRules_faction3_dmg_f0: '0',
	g_gameRules_faction3_dmg_f1: '1',
	g_gameRules_faction3_dmg_f2: '0',
	g_gameRules_faction3_dmg_f3: '1',
	g_gameRules_faction3_dmg_f4: '1',
	g_gameRules_faction3_dmg_f5: '1',
	g_gameRules_faction3_dmg_f6: '1',
	g_gameRules_faction4: '1',
	g_gameRules_faction4_name: 'outlaws',
	g_gameRules_faction4_steamids: '',
	g_gameRules_faction4_dmg_f0: '1',
	g_gameRules_faction4_dmg_f1: '1',
	g_gameRules_faction4_dmg_f2: '1',
	g_gameRules_faction4_dmg_f3: '1',
	g_gameRules_faction4_dmg_f4: '1',
	g_gameRules_faction4_dmg_f5: '1',
	g_gameRules_faction4_dmg_f6: '1',
	g_gameRules_faction5: '0',
	g_gameRules_faction5_name: 'military',
	g_gameRules_faction5_steamids: '',
	g_gameRules_faction5_dmg_f0: '1',
	g_gameRules_faction5_dmg_f1: '1',
	g_gameRules_faction5_dmg_f2: '1',
	g_gameRules_faction5_dmg_f3: '1',
	g_gameRules_faction5_dmg_f4: '1',
	g_gameRules_faction5_dmg_f5: '1',
	g_gameRules_faction5_dmg_f6: '1',
	g_gameRules_faction6: '0',
	g_gameRules_faction6_name: 'corporate',
	g_gameRules_faction6_steamids: '',
	g_gameRules_faction6_dmg_f0: '1',
	g_gameRules_faction6_dmg_f1: '1',
	g_gameRules_faction6_dmg_f2: '1',
	g_gameRules_faction6_dmg_f3: '1',
	g_gameRules_faction6_dmg_f4: '1',
	g_gameRules_faction6_dmg_f5: '1',
	g_gameRules_faction6_dmg_f6: '1',
};

test('normalizeGameRules using defaultFactionRules', () => {
	expect(utils.normalizeGameRules()).toEqual(mockGameRules);
});

test('normalizeGameRules using lawmen outlaw template', () => {
	expect(utils.normalizeGameRules(factionGameRulesLawmenOutlawFactionTemplate)).toEqual(
		mockGameRulesLawmenOutlawFactionTemplate
	);
});
